version: "3.4"

services:
  # Test API
  ecommerceapi-test:
    image: ecommerceapi-test
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb-test:27017/e-commerce
    ports:
      - 5001:5000
    volumes:
      - .:/usr/src/app
    command: ["npm", "test"]
    links:
      - ecommerceapi-mongodb-test
  # Test MongoDB
  ecommerceapi-mongodb-test:
    image: mongo:latest
    ports:
      - 27018:27017
    command: mongod --quiet --logpath /dev/null
  # Dev API
  ecommerceapi:
    image: ecommerceapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/e-commerce
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "dev"]
    links:
      - ecommerceapi-mongodb
  # Dev MongoDB
  ecommerceapi-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  data:
