version: "3.4"

services:
  ecommerceapi-test:
    image: ecommerceapi-test
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5001:5000
    volumes:
      - .:/usr/src/app
    command: ["npm", "test"]
    links:
      - mongodb-test
  mongodb-test:
    image: mongo:latest
    ports:
      - 27018:27017
    command: mongod --quiet --logpath /dev/null
  ecommerceapi:
    image: ecommerceapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "dev"]
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  data:
